package cadiboo.wiptech;

import cadiboo.wiptech.block.BlockEnamel;
import cadiboo.wiptech.block.BlockItem;
import cadiboo.wiptech.block.BlockModOre;
import cadiboo.wiptech.block.BlockResource;
import cadiboo.wiptech.block.BlockSpool;
import cadiboo.wiptech.block.BlockWire;
import cadiboo.wiptech.init.ModBlocks;
import cadiboo.wiptech.init.ModItems;
import cadiboo.wiptech.item.ItemCoil;
import cadiboo.wiptech.item.ItemModArmor;
import cadiboo.wiptech.item.ItemModAxe;
import cadiboo.wiptech.item.ItemModPickaxe;
import cadiboo.wiptech.item.ItemModShovel;
import cadiboo.wiptech.item.ItemModSword;
import cadiboo.wiptech.item.ItemRail;
import cadiboo.wiptech.util.ModEnums.BlockItemTypes;
import cadiboo.wiptech.util.ModEnums.ModMaterials;
import cadiboo.wiptech.util.ModReference;
import cadiboo.wiptech.util.ModUtil;
import net.minecraft.block.Block;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import net.minecraftforge.registries.IForgeRegistry;

@Mod.EventBusSubscriber(modid = ModReference.ID)
public final class EventSubscriber {

	@SubscribeEvent
	public static void onRegisterBlocksEvent(final RegistryEvent.Register<Block> event) {
		ModUtil.infoModMaterialsCode();
		final IForgeRegistry<Block> registry = event.getRegistry();

		registry.register(new BlockModOre(ModMaterials.URANIUM));
		registry.register(new BlockResource(ModMaterials.URANIUM));
		registry.register(new BlockItem(ModMaterials.URANIUM, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.URANIUM, BlockItemTypes.NUGGET));
		registry.register(new BlockModOre(ModMaterials.TUNGSTEN));
		registry.register(new BlockResource(ModMaterials.TUNGSTEN));
		registry.register(new BlockItem(ModMaterials.TUNGSTEN, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.TUNGSTEN, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.TUNGSTEN));
		registry.register(new BlockEnamel(ModMaterials.TUNGSTEN));
		registry.register(new BlockSpool(ModMaterials.TUNGSTEN));
		registry.register(new BlockModOre(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new BlockResource(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new BlockItem(ModMaterials.TUNGSTEN_CARBITE, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.TUNGSTEN_CARBITE, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new BlockEnamel(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new BlockSpool(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new BlockModOre(ModMaterials.TITANIUM));
		registry.register(new BlockResource(ModMaterials.TITANIUM));
		registry.register(new BlockItem(ModMaterials.TITANIUM, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.TITANIUM, BlockItemTypes.NUGGET));
		registry.register(new BlockModOre(ModMaterials.TIN));
		registry.register(new BlockResource(ModMaterials.TIN));
		registry.register(new BlockItem(ModMaterials.TIN, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.TIN, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.TIN));
		registry.register(new BlockEnamel(ModMaterials.TIN));
		registry.register(new BlockSpool(ModMaterials.TIN));
		registry.register(new BlockModOre(ModMaterials.THORIUM));
		registry.register(new BlockResource(ModMaterials.THORIUM));
		registry.register(new BlockItem(ModMaterials.THORIUM, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.THORIUM, BlockItemTypes.NUGGET));
		registry.register(new BlockModOre(ModMaterials.SILVER));
		registry.register(new BlockResource(ModMaterials.SILVER));
		registry.register(new BlockItem(ModMaterials.SILVER, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.SILVER, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.SILVER));
		registry.register(new BlockEnamel(ModMaterials.SILVER));
		registry.register(new BlockSpool(ModMaterials.SILVER));
		registry.register(new BlockModOre(ModMaterials.PLATINUM));
		registry.register(new BlockResource(ModMaterials.PLATINUM));
		registry.register(new BlockItem(ModMaterials.PLATINUM, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.PLATINUM, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.PLATINUM));
		registry.register(new BlockEnamel(ModMaterials.PLATINUM));
		registry.register(new BlockSpool(ModMaterials.PLATINUM));
		registry.register(new BlockModOre(ModMaterials.PLUTONIUM));
		registry.register(new BlockResource(ModMaterials.PLUTONIUM));
		registry.register(new BlockItem(ModMaterials.PLUTONIUM, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.PLUTONIUM, BlockItemTypes.NUGGET));
		registry.register(new BlockModOre(ModMaterials.OSMIUM));
		registry.register(new BlockResource(ModMaterials.OSMIUM));
		registry.register(new BlockItem(ModMaterials.OSMIUM, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.OSMIUM, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.OSMIUM));
		registry.register(new BlockEnamel(ModMaterials.OSMIUM));
		registry.register(new BlockSpool(ModMaterials.OSMIUM));
		registry.register(new BlockModOre(ModMaterials.NICKEL));
		registry.register(new BlockResource(ModMaterials.NICKEL));
		registry.register(new BlockItem(ModMaterials.NICKEL, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.NICKEL, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.NICKEL));
		registry.register(new BlockEnamel(ModMaterials.NICKEL));
		registry.register(new BlockSpool(ModMaterials.NICKEL));
		registry.register(new BlockModOre(ModMaterials.STEEL));
		registry.register(new BlockResource(ModMaterials.STEEL));
		registry.register(new BlockItem(ModMaterials.STEEL, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.STEEL, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.STEEL));
		registry.register(new BlockEnamel(ModMaterials.STEEL));
		registry.register(new BlockSpool(ModMaterials.STEEL));
		registry.register(new BlockModOre(ModMaterials.ALUMINUM));
		registry.register(new BlockResource(ModMaterials.ALUMINUM));
		registry.register(new BlockItem(ModMaterials.ALUMINUM, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.ALUMINUM, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.ALUMINUM));
		registry.register(new BlockEnamel(ModMaterials.ALUMINUM));
		registry.register(new BlockSpool(ModMaterials.ALUMINUM));
		registry.register(new BlockModOre(ModMaterials.COPPER));
		registry.register(new BlockResource(ModMaterials.COPPER));
		registry.register(new BlockItem(ModMaterials.COPPER, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.COPPER, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.COPPER));
		registry.register(new BlockEnamel(ModMaterials.COPPER));
		registry.register(new BlockSpool(ModMaterials.COPPER));
		registry.register(new BlockModOre(ModMaterials.GOLD));
		registry.register(new BlockResource(ModMaterials.GOLD));
		registry.register(new BlockItem(ModMaterials.GOLD, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.GOLD, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.GOLD));
		registry.register(new BlockEnamel(ModMaterials.GOLD));
		registry.register(new BlockSpool(ModMaterials.GOLD));
		registry.register(new BlockModOre(ModMaterials.IRON));
		registry.register(new BlockResource(ModMaterials.IRON));
		registry.register(new BlockItem(ModMaterials.IRON, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.IRON, BlockItemTypes.NUGGET));
		registry.register(new BlockWire(ModMaterials.IRON));
		registry.register(new BlockEnamel(ModMaterials.IRON));
		registry.register(new BlockSpool(ModMaterials.IRON));
		registry.register(new BlockModOre(ModMaterials.LEAD));
		registry.register(new BlockResource(ModMaterials.LEAD));
		registry.register(new BlockItem(ModMaterials.LEAD, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.LEAD, BlockItemTypes.NUGGET));
		registry.register(new BlockModOre(ModMaterials.GALLIUM));
		registry.register(new BlockResource(ModMaterials.GALLIUM));
		registry.register(new BlockItem(ModMaterials.GALLIUM, BlockItemTypes.INGOT));
		registry.register(new BlockItem(ModMaterials.GALLIUM, BlockItemTypes.NUGGET));

	}

	@SubscribeEvent
	public static void onRegisterItemsEvent(final RegistryEvent.Register<Item> event) {
		final IForgeRegistry<Item> registry = event.getRegistry();

		registry.register(new ItemBlock(ModBlocks.URANIUM_ORE).setRegistryName(ModBlocks.URANIUM_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.URANIUM_BLOCK).setRegistryName(ModBlocks.URANIUM_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.URANIUM_INGOT).setRegistryName(ModBlocks.URANIUM_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.URANIUM_NUGGET).setRegistryName(ModBlocks.URANIUM_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.URANIUM, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.URANIUM, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.URANIUM, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.URANIUM, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.URANIUM));
		registry.register(new ItemModAxe(ModMaterials.URANIUM));
		registry.register(new ItemModSword(ModMaterials.URANIUM));
		registry.register(new ItemModShovel(ModMaterials.URANIUM));
		registry.register(new ItemBlock(ModBlocks.TUNGSTEN_ORE).setRegistryName(ModBlocks.TUNGSTEN_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TUNGSTEN_BLOCK).setRegistryName(ModBlocks.TUNGSTEN_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TUNGSTEN_INGOT).setRegistryName(ModBlocks.TUNGSTEN_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TUNGSTEN_NUGGET).setRegistryName(ModBlocks.TUNGSTEN_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.TUNGSTEN, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.TUNGSTEN, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.TUNGSTEN, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.TUNGSTEN, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.TUNGSTEN));
		registry.register(new ItemModAxe(ModMaterials.TUNGSTEN));
		registry.register(new ItemModSword(ModMaterials.TUNGSTEN));
		registry.register(new ItemModShovel(ModMaterials.TUNGSTEN));
		registry.register(new ItemCoil(ModMaterials.TUNGSTEN));
		registry.register(new ItemBlock(ModBlocks.TUNGSTEN_SPOOL).setRegistryName(ModBlocks.TUNGSTEN_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.TUNGSTEN));
		registry.register(new ItemBlock(ModBlocks.TUNGSTEN_CARBITE_ORE).setRegistryName(ModBlocks.TUNGSTEN_CARBITE_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TUNGSTEN_CARBITE_BLOCK).setRegistryName(ModBlocks.TUNGSTEN_CARBITE_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TUNGSTEN_CARBITE_INGOT).setRegistryName(ModBlocks.TUNGSTEN_CARBITE_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TUNGSTEN_CARBITE_NUGGET).setRegistryName(ModBlocks.TUNGSTEN_CARBITE_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.TUNGSTEN_CARBITE, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.TUNGSTEN_CARBITE, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.TUNGSTEN_CARBITE, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.TUNGSTEN_CARBITE, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new ItemModAxe(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new ItemModSword(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new ItemModShovel(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new ItemCoil(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new ItemBlock(ModBlocks.TUNGSTEN_CARBITE_SPOOL).setRegistryName(ModBlocks.TUNGSTEN_CARBITE_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.TUNGSTEN_CARBITE));
		registry.register(new ItemBlock(ModBlocks.TITANIUM_ORE).setRegistryName(ModBlocks.TITANIUM_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TITANIUM_BLOCK).setRegistryName(ModBlocks.TITANIUM_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TITANIUM_INGOT).setRegistryName(ModBlocks.TITANIUM_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TITANIUM_NUGGET).setRegistryName(ModBlocks.TITANIUM_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.TITANIUM, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.TITANIUM, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.TITANIUM, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.TITANIUM, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.TITANIUM));
		registry.register(new ItemModAxe(ModMaterials.TITANIUM));
		registry.register(new ItemModSword(ModMaterials.TITANIUM));
		registry.register(new ItemModShovel(ModMaterials.TITANIUM));
		registry.register(new ItemBlock(ModBlocks.TIN_ORE).setRegistryName(ModBlocks.TIN_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TIN_BLOCK).setRegistryName(ModBlocks.TIN_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TIN_INGOT).setRegistryName(ModBlocks.TIN_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.TIN_NUGGET).setRegistryName(ModBlocks.TIN_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.TIN, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.TIN, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.TIN, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.TIN, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.TIN));
		registry.register(new ItemModAxe(ModMaterials.TIN));
		registry.register(new ItemModSword(ModMaterials.TIN));
		registry.register(new ItemModShovel(ModMaterials.TIN));
		registry.register(new ItemCoil(ModMaterials.TIN));
		registry.register(new ItemBlock(ModBlocks.TIN_SPOOL).setRegistryName(ModBlocks.TIN_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.TIN));
		registry.register(new ItemBlock(ModBlocks.THORIUM_ORE).setRegistryName(ModBlocks.THORIUM_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.THORIUM_BLOCK).setRegistryName(ModBlocks.THORIUM_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.THORIUM_INGOT).setRegistryName(ModBlocks.THORIUM_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.THORIUM_NUGGET).setRegistryName(ModBlocks.THORIUM_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.THORIUM, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.THORIUM, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.THORIUM, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.THORIUM, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.THORIUM));
		registry.register(new ItemModAxe(ModMaterials.THORIUM));
		registry.register(new ItemModSword(ModMaterials.THORIUM));
		registry.register(new ItemModShovel(ModMaterials.THORIUM));
		registry.register(new ItemBlock(ModBlocks.SILVER_ORE).setRegistryName(ModBlocks.SILVER_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.SILVER_BLOCK).setRegistryName(ModBlocks.SILVER_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.SILVER_INGOT).setRegistryName(ModBlocks.SILVER_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.SILVER_NUGGET).setRegistryName(ModBlocks.SILVER_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.SILVER, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.SILVER, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.SILVER, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.SILVER, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.SILVER));
		registry.register(new ItemModAxe(ModMaterials.SILVER));
		registry.register(new ItemModSword(ModMaterials.SILVER));
		registry.register(new ItemModShovel(ModMaterials.SILVER));
		registry.register(new ItemCoil(ModMaterials.SILVER));
		registry.register(new ItemBlock(ModBlocks.SILVER_SPOOL).setRegistryName(ModBlocks.SILVER_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.SILVER));
		registry.register(new ItemBlock(ModBlocks.PLATINUM_ORE).setRegistryName(ModBlocks.PLATINUM_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.PLATINUM_BLOCK).setRegistryName(ModBlocks.PLATINUM_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.PLATINUM_INGOT).setRegistryName(ModBlocks.PLATINUM_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.PLATINUM_NUGGET).setRegistryName(ModBlocks.PLATINUM_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.PLATINUM, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.PLATINUM, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.PLATINUM, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.PLATINUM, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.PLATINUM));
		registry.register(new ItemModAxe(ModMaterials.PLATINUM));
		registry.register(new ItemModSword(ModMaterials.PLATINUM));
		registry.register(new ItemModShovel(ModMaterials.PLATINUM));
		registry.register(new ItemCoil(ModMaterials.PLATINUM));
		registry.register(new ItemBlock(ModBlocks.PLATINUM_SPOOL).setRegistryName(ModBlocks.PLATINUM_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.PLATINUM));
		registry.register(new ItemBlock(ModBlocks.PLUTONIUM_ORE).setRegistryName(ModBlocks.PLUTONIUM_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.PLUTONIUM_BLOCK).setRegistryName(ModBlocks.PLUTONIUM_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.PLUTONIUM_INGOT).setRegistryName(ModBlocks.PLUTONIUM_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.PLUTONIUM_NUGGET).setRegistryName(ModBlocks.PLUTONIUM_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.PLUTONIUM, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.PLUTONIUM, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.PLUTONIUM, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.PLUTONIUM, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.PLUTONIUM));
		registry.register(new ItemModAxe(ModMaterials.PLUTONIUM));
		registry.register(new ItemModSword(ModMaterials.PLUTONIUM));
		registry.register(new ItemModShovel(ModMaterials.PLUTONIUM));
		registry.register(new ItemBlock(ModBlocks.OSMIUM_ORE).setRegistryName(ModBlocks.OSMIUM_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.OSMIUM_BLOCK).setRegistryName(ModBlocks.OSMIUM_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.OSMIUM_INGOT).setRegistryName(ModBlocks.OSMIUM_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.OSMIUM_NUGGET).setRegistryName(ModBlocks.OSMIUM_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.OSMIUM, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.OSMIUM, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.OSMIUM, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.OSMIUM, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.OSMIUM));
		registry.register(new ItemModAxe(ModMaterials.OSMIUM));
		registry.register(new ItemModSword(ModMaterials.OSMIUM));
		registry.register(new ItemModShovel(ModMaterials.OSMIUM));
		registry.register(new ItemCoil(ModMaterials.OSMIUM));
		registry.register(new ItemBlock(ModBlocks.OSMIUM_SPOOL).setRegistryName(ModBlocks.OSMIUM_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.OSMIUM));
		registry.register(new ItemBlock(ModBlocks.NICKEL_ORE).setRegistryName(ModBlocks.NICKEL_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.NICKEL_BLOCK).setRegistryName(ModBlocks.NICKEL_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.NICKEL_INGOT).setRegistryName(ModBlocks.NICKEL_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.NICKEL_NUGGET).setRegistryName(ModBlocks.NICKEL_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.NICKEL, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.NICKEL, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.NICKEL, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.NICKEL, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.NICKEL));
		registry.register(new ItemModAxe(ModMaterials.NICKEL));
		registry.register(new ItemModSword(ModMaterials.NICKEL));
		registry.register(new ItemModShovel(ModMaterials.NICKEL));
		registry.register(new ItemCoil(ModMaterials.NICKEL));
		registry.register(new ItemBlock(ModBlocks.NICKEL_SPOOL).setRegistryName(ModBlocks.NICKEL_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.NICKEL));
		registry.register(new ItemBlock(ModBlocks.STEEL_ORE).setRegistryName(ModBlocks.STEEL_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.STEEL_BLOCK).setRegistryName(ModBlocks.STEEL_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.STEEL_INGOT).setRegistryName(ModBlocks.STEEL_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.STEEL_NUGGET).setRegistryName(ModBlocks.STEEL_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.STEEL, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.STEEL, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.STEEL, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.STEEL, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.STEEL));
		registry.register(new ItemModAxe(ModMaterials.STEEL));
		registry.register(new ItemModSword(ModMaterials.STEEL));
		registry.register(new ItemModShovel(ModMaterials.STEEL));
		registry.register(new ItemCoil(ModMaterials.STEEL));
		registry.register(new ItemBlock(ModBlocks.STEEL_SPOOL).setRegistryName(ModBlocks.STEEL_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.STEEL));
		registry.register(new ItemBlock(ModBlocks.ALUMINUM_ORE).setRegistryName(ModBlocks.ALUMINUM_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.ALUMINUM_BLOCK).setRegistryName(ModBlocks.ALUMINUM_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.ALUMINUM_INGOT).setRegistryName(ModBlocks.ALUMINUM_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.ALUMINUM_NUGGET).setRegistryName(ModBlocks.ALUMINUM_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.ALUMINUM, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.ALUMINUM, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.ALUMINUM, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.ALUMINUM, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.ALUMINUM));
		registry.register(new ItemModAxe(ModMaterials.ALUMINUM));
		registry.register(new ItemModSword(ModMaterials.ALUMINUM));
		registry.register(new ItemModShovel(ModMaterials.ALUMINUM));
		registry.register(new ItemCoil(ModMaterials.ALUMINUM));
		registry.register(new ItemBlock(ModBlocks.ALUMINUM_SPOOL).setRegistryName(ModBlocks.ALUMINUM_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.ALUMINUM));
		registry.register(new ItemBlock(ModBlocks.COPPER_ORE).setRegistryName(ModBlocks.COPPER_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.COPPER_BLOCK).setRegistryName(ModBlocks.COPPER_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.COPPER_INGOT).setRegistryName(ModBlocks.COPPER_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.COPPER_NUGGET).setRegistryName(ModBlocks.COPPER_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.COPPER, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.COPPER, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.COPPER, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.COPPER, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.COPPER));
		registry.register(new ItemModAxe(ModMaterials.COPPER));
		registry.register(new ItemModSword(ModMaterials.COPPER));
		registry.register(new ItemModShovel(ModMaterials.COPPER));
		registry.register(new ItemCoil(ModMaterials.COPPER));
		registry.register(new ItemBlock(ModBlocks.COPPER_SPOOL).setRegistryName(ModBlocks.COPPER_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.COPPER));
		registry.register(new ItemBlock(ModBlocks.GOLD_ORE).setRegistryName(ModBlocks.GOLD_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.GOLD_BLOCK).setRegistryName(ModBlocks.GOLD_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.GOLD_INGOT).setRegistryName(ModBlocks.GOLD_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.GOLD_NUGGET).setRegistryName(ModBlocks.GOLD_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.GOLD, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.GOLD, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.GOLD, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.GOLD, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.GOLD));
		registry.register(new ItemModAxe(ModMaterials.GOLD));
		registry.register(new ItemModSword(ModMaterials.GOLD));
		registry.register(new ItemModShovel(ModMaterials.GOLD));
		registry.register(new ItemCoil(ModMaterials.GOLD));
		registry.register(new ItemBlock(ModBlocks.GOLD_SPOOL).setRegistryName(ModBlocks.GOLD_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.GOLD));
		registry.register(new ItemBlock(ModBlocks.IRON_ORE).setRegistryName(ModBlocks.IRON_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.IRON_BLOCK).setRegistryName(ModBlocks.IRON_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.IRON_INGOT).setRegistryName(ModBlocks.IRON_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.IRON_NUGGET).setRegistryName(ModBlocks.IRON_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.IRON, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.IRON, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.IRON, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.IRON, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.IRON));
		registry.register(new ItemModAxe(ModMaterials.IRON));
		registry.register(new ItemModSword(ModMaterials.IRON));
		registry.register(new ItemModShovel(ModMaterials.IRON));
		registry.register(new ItemCoil(ModMaterials.IRON));
		registry.register(new ItemBlock(ModBlocks.IRON_SPOOL).setRegistryName(ModBlocks.IRON_SPOOL.getRegistryName()));
		registry.register(new ItemRail(ModMaterials.IRON));
		registry.register(new ItemBlock(ModBlocks.LEAD_ORE).setRegistryName(ModBlocks.LEAD_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.LEAD_BLOCK).setRegistryName(ModBlocks.LEAD_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.LEAD_INGOT).setRegistryName(ModBlocks.LEAD_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.LEAD_NUGGET).setRegistryName(ModBlocks.LEAD_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.LEAD, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.LEAD, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.LEAD, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.LEAD, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.LEAD));
		registry.register(new ItemModAxe(ModMaterials.LEAD));
		registry.register(new ItemModSword(ModMaterials.LEAD));
		registry.register(new ItemModShovel(ModMaterials.LEAD));
		registry.register(new ItemBlock(ModBlocks.GALLIUM_ORE).setRegistryName(ModBlocks.GALLIUM_ORE.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.GALLIUM_BLOCK).setRegistryName(ModBlocks.GALLIUM_BLOCK.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.GALLIUM_INGOT).setRegistryName(ModBlocks.GALLIUM_INGOT.getRegistryName()));
		registry.register(new ItemBlock(ModBlocks.GALLIUM_NUGGET).setRegistryName(ModBlocks.GALLIUM_NUGGET.getRegistryName()));
		registry.register(new ItemModArmor(ModMaterials.GALLIUM, EntityEquipmentSlot.HEAD));
		registry.register(new ItemModArmor(ModMaterials.GALLIUM, EntityEquipmentSlot.CHEST));
		registry.register(new ItemModArmor(ModMaterials.GALLIUM, EntityEquipmentSlot.LEGS));
		registry.register(new ItemModArmor(ModMaterials.GALLIUM, EntityEquipmentSlot.FEET));
		registry.register(new ItemModPickaxe(ModMaterials.GALLIUM));
		registry.register(new ItemModAxe(ModMaterials.GALLIUM));
		registry.register(new ItemModSword(ModMaterials.GALLIUM));
		registry.register(new ItemModShovel(ModMaterials.GALLIUM));

	}

	@SubscribeEvent
	@SideOnly(Side.CLIENT)
	public static final void onRegisterModelsEvent(final ModelRegistryEvent event) {

		registerItemBlockModel(ModBlocks.URANIUM_ORE);
		registerItemBlockModel(ModBlocks.URANIUM_BLOCK);
		registerItemBlockModel(ModBlocks.URANIUM_INGOT);
		registerItemBlockModel(ModBlocks.URANIUM_NUGGET);
		registerItemModel(ModItems.URANIUM_HELMET);
		registerItemModel(ModItems.URANIUM_CHESTPLATE);
		registerItemModel(ModItems.URANIUM_LEGGINGS);
		registerItemModel(ModItems.URANIUM_BOOTS);
		registerItemModel(ModItems.URANIUM_PICKAXE);
		registerItemModel(ModItems.URANIUM_AXE);
		registerItemModel(ModItems.URANIUM_SWORD);
		registerItemModel(ModItems.URANIUM_SHOVEL);
		registerItemBlockModel(ModBlocks.TUNGSTEN_ORE);
		registerItemBlockModel(ModBlocks.TUNGSTEN_BLOCK);
		registerItemBlockModel(ModBlocks.TUNGSTEN_INGOT);
		registerItemBlockModel(ModBlocks.TUNGSTEN_NUGGET);
		registerItemModel(ModItems.TUNGSTEN_HELMET);
		registerItemModel(ModItems.TUNGSTEN_CHESTPLATE);
		registerItemModel(ModItems.TUNGSTEN_LEGGINGS);
		registerItemModel(ModItems.TUNGSTEN_BOOTS);
		registerItemModel(ModItems.TUNGSTEN_PICKAXE);
		registerItemModel(ModItems.TUNGSTEN_AXE);
		registerItemModel(ModItems.TUNGSTEN_SWORD);
		registerItemModel(ModItems.TUNGSTEN_SHOVEL);
		registerItemBlockModel(ModBlocks.TUNGSTEN_WIRE);
		registerItemBlockModel(ModBlocks.TUNGSTEN_ENAMEL);
		registerItemModel(ModItems.TUNGSTEN_COIL);
		registerItemBlockModel(ModBlocks.TUNGSTEN_SPOOL);
		registerItemModel(ModItems.TUNGSTEN_RAIL);
		registerItemBlockModel(ModBlocks.TUNGSTEN_CARBITE_ORE);
		registerItemBlockModel(ModBlocks.TUNGSTEN_CARBITE_BLOCK);
		registerItemBlockModel(ModBlocks.TUNGSTEN_CARBITE_INGOT);
		registerItemBlockModel(ModBlocks.TUNGSTEN_CARBITE_NUGGET);
		registerItemModel(ModItems.TUNGSTEN_CARBITE_HELMET);
		registerItemModel(ModItems.TUNGSTEN_CARBITE_CHESTPLATE);
		registerItemModel(ModItems.TUNGSTEN_CARBITE_LEGGINGS);
		registerItemModel(ModItems.TUNGSTEN_CARBITE_BOOTS);
		registerItemModel(ModItems.TUNGSTEN_CARBITE_PICKAXE);
		registerItemModel(ModItems.TUNGSTEN_CARBITE_AXE);
		registerItemModel(ModItems.TUNGSTEN_CARBITE_SWORD);
		registerItemModel(ModItems.TUNGSTEN_CARBITE_SHOVEL);
		registerItemBlockModel(ModBlocks.TUNGSTEN_CARBITE_WIRE);
		registerItemBlockModel(ModBlocks.TUNGSTEN_CARBITE_ENAMEL);
		registerItemModel(ModItems.TUNGSTEN_CARBITE_COIL);
		registerItemBlockModel(ModBlocks.TUNGSTEN_CARBITE_SPOOL);
		registerItemModel(ModItems.TUNGSTEN_CARBITE_RAIL);
		registerItemBlockModel(ModBlocks.TITANIUM_ORE);
		registerItemBlockModel(ModBlocks.TITANIUM_BLOCK);
		registerItemBlockModel(ModBlocks.TITANIUM_INGOT);
		registerItemBlockModel(ModBlocks.TITANIUM_NUGGET);
		registerItemModel(ModItems.TITANIUM_HELMET);
		registerItemModel(ModItems.TITANIUM_CHESTPLATE);
		registerItemModel(ModItems.TITANIUM_LEGGINGS);
		registerItemModel(ModItems.TITANIUM_BOOTS);
		registerItemModel(ModItems.TITANIUM_PICKAXE);
		registerItemModel(ModItems.TITANIUM_AXE);
		registerItemModel(ModItems.TITANIUM_SWORD);
		registerItemModel(ModItems.TITANIUM_SHOVEL);
		registerItemBlockModel(ModBlocks.TIN_ORE);
		registerItemBlockModel(ModBlocks.TIN_BLOCK);
		registerItemBlockModel(ModBlocks.TIN_INGOT);
		registerItemBlockModel(ModBlocks.TIN_NUGGET);
		registerItemModel(ModItems.TIN_HELMET);
		registerItemModel(ModItems.TIN_CHESTPLATE);
		registerItemModel(ModItems.TIN_LEGGINGS);
		registerItemModel(ModItems.TIN_BOOTS);
		registerItemModel(ModItems.TIN_PICKAXE);
		registerItemModel(ModItems.TIN_AXE);
		registerItemModel(ModItems.TIN_SWORD);
		registerItemModel(ModItems.TIN_SHOVEL);
		registerItemBlockModel(ModBlocks.TIN_WIRE);
		registerItemBlockModel(ModBlocks.TIN_ENAMEL);
		registerItemModel(ModItems.TIN_COIL);
		registerItemBlockModel(ModBlocks.TIN_SPOOL);
		registerItemModel(ModItems.TIN_RAIL);
		registerItemBlockModel(ModBlocks.THORIUM_ORE);
		registerItemBlockModel(ModBlocks.THORIUM_BLOCK);
		registerItemBlockModel(ModBlocks.THORIUM_INGOT);
		registerItemBlockModel(ModBlocks.THORIUM_NUGGET);
		registerItemModel(ModItems.THORIUM_HELMET);
		registerItemModel(ModItems.THORIUM_CHESTPLATE);
		registerItemModel(ModItems.THORIUM_LEGGINGS);
		registerItemModel(ModItems.THORIUM_BOOTS);
		registerItemModel(ModItems.THORIUM_PICKAXE);
		registerItemModel(ModItems.THORIUM_AXE);
		registerItemModel(ModItems.THORIUM_SWORD);
		registerItemModel(ModItems.THORIUM_SHOVEL);
		registerItemBlockModel(ModBlocks.SILVER_ORE);
		registerItemBlockModel(ModBlocks.SILVER_BLOCK);
		registerItemBlockModel(ModBlocks.SILVER_INGOT);
		registerItemBlockModel(ModBlocks.SILVER_NUGGET);
		registerItemModel(ModItems.SILVER_HELMET);
		registerItemModel(ModItems.SILVER_CHESTPLATE);
		registerItemModel(ModItems.SILVER_LEGGINGS);
		registerItemModel(ModItems.SILVER_BOOTS);
		registerItemModel(ModItems.SILVER_PICKAXE);
		registerItemModel(ModItems.SILVER_AXE);
		registerItemModel(ModItems.SILVER_SWORD);
		registerItemModel(ModItems.SILVER_SHOVEL);
		registerItemBlockModel(ModBlocks.SILVER_WIRE);
		registerItemBlockModel(ModBlocks.SILVER_ENAMEL);
		registerItemModel(ModItems.SILVER_COIL);
		registerItemBlockModel(ModBlocks.SILVER_SPOOL);
		registerItemModel(ModItems.SILVER_RAIL);
		registerItemBlockModel(ModBlocks.PLATINUM_ORE);
		registerItemBlockModel(ModBlocks.PLATINUM_BLOCK);
		registerItemBlockModel(ModBlocks.PLATINUM_INGOT);
		registerItemBlockModel(ModBlocks.PLATINUM_NUGGET);
		registerItemModel(ModItems.PLATINUM_HELMET);
		registerItemModel(ModItems.PLATINUM_CHESTPLATE);
		registerItemModel(ModItems.PLATINUM_LEGGINGS);
		registerItemModel(ModItems.PLATINUM_BOOTS);
		registerItemModel(ModItems.PLATINUM_PICKAXE);
		registerItemModel(ModItems.PLATINUM_AXE);
		registerItemModel(ModItems.PLATINUM_SWORD);
		registerItemModel(ModItems.PLATINUM_SHOVEL);
		registerItemBlockModel(ModBlocks.PLATINUM_WIRE);
		registerItemBlockModel(ModBlocks.PLATINUM_ENAMEL);
		registerItemModel(ModItems.PLATINUM_COIL);
		registerItemBlockModel(ModBlocks.PLATINUM_SPOOL);
		registerItemModel(ModItems.PLATINUM_RAIL);
		registerItemBlockModel(ModBlocks.PLUTONIUM_ORE);
		registerItemBlockModel(ModBlocks.PLUTONIUM_BLOCK);
		registerItemBlockModel(ModBlocks.PLUTONIUM_INGOT);
		registerItemBlockModel(ModBlocks.PLUTONIUM_NUGGET);
		registerItemModel(ModItems.PLUTONIUM_HELMET);
		registerItemModel(ModItems.PLUTONIUM_CHESTPLATE);
		registerItemModel(ModItems.PLUTONIUM_LEGGINGS);
		registerItemModel(ModItems.PLUTONIUM_BOOTS);
		registerItemModel(ModItems.PLUTONIUM_PICKAXE);
		registerItemModel(ModItems.PLUTONIUM_AXE);
		registerItemModel(ModItems.PLUTONIUM_SWORD);
		registerItemModel(ModItems.PLUTONIUM_SHOVEL);
		registerItemBlockModel(ModBlocks.OSMIUM_ORE);
		registerItemBlockModel(ModBlocks.OSMIUM_BLOCK);
		registerItemBlockModel(ModBlocks.OSMIUM_INGOT);
		registerItemBlockModel(ModBlocks.OSMIUM_NUGGET);
		registerItemModel(ModItems.OSMIUM_HELMET);
		registerItemModel(ModItems.OSMIUM_CHESTPLATE);
		registerItemModel(ModItems.OSMIUM_LEGGINGS);
		registerItemModel(ModItems.OSMIUM_BOOTS);
		registerItemModel(ModItems.OSMIUM_PICKAXE);
		registerItemModel(ModItems.OSMIUM_AXE);
		registerItemModel(ModItems.OSMIUM_SWORD);
		registerItemModel(ModItems.OSMIUM_SHOVEL);
		registerItemBlockModel(ModBlocks.OSMIUM_WIRE);
		registerItemBlockModel(ModBlocks.OSMIUM_ENAMEL);
		registerItemModel(ModItems.OSMIUM_COIL);
		registerItemBlockModel(ModBlocks.OSMIUM_SPOOL);
		registerItemModel(ModItems.OSMIUM_RAIL);
		registerItemBlockModel(ModBlocks.NICKEL_ORE);
		registerItemBlockModel(ModBlocks.NICKEL_BLOCK);
		registerItemBlockModel(ModBlocks.NICKEL_INGOT);
		registerItemBlockModel(ModBlocks.NICKEL_NUGGET);
		registerItemModel(ModItems.NICKEL_HELMET);
		registerItemModel(ModItems.NICKEL_CHESTPLATE);
		registerItemModel(ModItems.NICKEL_LEGGINGS);
		registerItemModel(ModItems.NICKEL_BOOTS);
		registerItemModel(ModItems.NICKEL_PICKAXE);
		registerItemModel(ModItems.NICKEL_AXE);
		registerItemModel(ModItems.NICKEL_SWORD);
		registerItemModel(ModItems.NICKEL_SHOVEL);
		registerItemBlockModel(ModBlocks.NICKEL_WIRE);
		registerItemBlockModel(ModBlocks.NICKEL_ENAMEL);
		registerItemModel(ModItems.NICKEL_COIL);
		registerItemBlockModel(ModBlocks.NICKEL_SPOOL);
		registerItemModel(ModItems.NICKEL_RAIL);
		registerItemBlockModel(ModBlocks.STEEL_ORE);
		registerItemBlockModel(ModBlocks.STEEL_BLOCK);
		registerItemBlockModel(ModBlocks.STEEL_INGOT);
		registerItemBlockModel(ModBlocks.STEEL_NUGGET);
		registerItemModel(ModItems.STEEL_HELMET);
		registerItemModel(ModItems.STEEL_CHESTPLATE);
		registerItemModel(ModItems.STEEL_LEGGINGS);
		registerItemModel(ModItems.STEEL_BOOTS);
		registerItemModel(ModItems.STEEL_PICKAXE);
		registerItemModel(ModItems.STEEL_AXE);
		registerItemModel(ModItems.STEEL_SWORD);
		registerItemModel(ModItems.STEEL_SHOVEL);
		registerItemBlockModel(ModBlocks.STEEL_WIRE);
		registerItemBlockModel(ModBlocks.STEEL_ENAMEL);
		registerItemModel(ModItems.STEEL_COIL);
		registerItemBlockModel(ModBlocks.STEEL_SPOOL);
		registerItemModel(ModItems.STEEL_RAIL);
		registerItemBlockModel(ModBlocks.ALUMINUM_ORE);
		registerItemBlockModel(ModBlocks.ALUMINUM_BLOCK);
		registerItemBlockModel(ModBlocks.ALUMINUM_INGOT);
		registerItemBlockModel(ModBlocks.ALUMINUM_NUGGET);
		registerItemModel(ModItems.ALUMINUM_HELMET);
		registerItemModel(ModItems.ALUMINUM_CHESTPLATE);
		registerItemModel(ModItems.ALUMINUM_LEGGINGS);
		registerItemModel(ModItems.ALUMINUM_BOOTS);
		registerItemModel(ModItems.ALUMINUM_PICKAXE);
		registerItemModel(ModItems.ALUMINUM_AXE);
		registerItemModel(ModItems.ALUMINUM_SWORD);
		registerItemModel(ModItems.ALUMINUM_SHOVEL);
		registerItemBlockModel(ModBlocks.ALUMINUM_WIRE);
		registerItemBlockModel(ModBlocks.ALUMINUM_ENAMEL);
		registerItemModel(ModItems.ALUMINUM_COIL);
		registerItemBlockModel(ModBlocks.ALUMINUM_SPOOL);
		registerItemModel(ModItems.ALUMINUM_RAIL);
		registerItemBlockModel(ModBlocks.COPPER_ORE);
		registerItemBlockModel(ModBlocks.COPPER_BLOCK);
		registerItemBlockModel(ModBlocks.COPPER_INGOT);
		registerItemBlockModel(ModBlocks.COPPER_NUGGET);
		registerItemModel(ModItems.COPPER_HELMET);
		registerItemModel(ModItems.COPPER_CHESTPLATE);
		registerItemModel(ModItems.COPPER_LEGGINGS);
		registerItemModel(ModItems.COPPER_BOOTS);
		registerItemModel(ModItems.COPPER_PICKAXE);
		registerItemModel(ModItems.COPPER_AXE);
		registerItemModel(ModItems.COPPER_SWORD);
		registerItemModel(ModItems.COPPER_SHOVEL);
		registerItemBlockModel(ModBlocks.COPPER_WIRE);
		registerItemBlockModel(ModBlocks.COPPER_ENAMEL);
		registerItemModel(ModItems.COPPER_COIL);
		registerItemBlockModel(ModBlocks.COPPER_SPOOL);
		registerItemModel(ModItems.COPPER_RAIL);
		registerItemBlockModel(ModBlocks.GOLD_ORE);
		registerItemBlockModel(ModBlocks.GOLD_BLOCK);
		registerItemBlockModel(ModBlocks.GOLD_INGOT);
		registerItemBlockModel(ModBlocks.GOLD_NUGGET);
		registerItemModel(ModItems.GOLD_HELMET);
		registerItemModel(ModItems.GOLD_CHESTPLATE);
		registerItemModel(ModItems.GOLD_LEGGINGS);
		registerItemModel(ModItems.GOLD_BOOTS);
		registerItemModel(ModItems.GOLD_PICKAXE);
		registerItemModel(ModItems.GOLD_AXE);
		registerItemModel(ModItems.GOLD_SWORD);
		registerItemModel(ModItems.GOLD_SHOVEL);
		registerItemBlockModel(ModBlocks.GOLD_WIRE);
		registerItemBlockModel(ModBlocks.GOLD_ENAMEL);
		registerItemModel(ModItems.GOLD_COIL);
		registerItemBlockModel(ModBlocks.GOLD_SPOOL);
		registerItemModel(ModItems.GOLD_RAIL);
		registerItemBlockModel(ModBlocks.IRON_ORE);
		registerItemBlockModel(ModBlocks.IRON_BLOCK);
		registerItemBlockModel(ModBlocks.IRON_INGOT);
		registerItemBlockModel(ModBlocks.IRON_NUGGET);
		registerItemModel(ModItems.IRON_HELMET);
		registerItemModel(ModItems.IRON_CHESTPLATE);
		registerItemModel(ModItems.IRON_LEGGINGS);
		registerItemModel(ModItems.IRON_BOOTS);
		registerItemModel(ModItems.IRON_PICKAXE);
		registerItemModel(ModItems.IRON_AXE);
		registerItemModel(ModItems.IRON_SWORD);
		registerItemModel(ModItems.IRON_SHOVEL);
		registerItemBlockModel(ModBlocks.IRON_WIRE);
		registerItemBlockModel(ModBlocks.IRON_ENAMEL);
		registerItemModel(ModItems.IRON_COIL);
		registerItemBlockModel(ModBlocks.IRON_SPOOL);
		registerItemModel(ModItems.IRON_RAIL);
		registerItemBlockModel(ModBlocks.LEAD_ORE);
		registerItemBlockModel(ModBlocks.LEAD_BLOCK);
		registerItemBlockModel(ModBlocks.LEAD_INGOT);
		registerItemBlockModel(ModBlocks.LEAD_NUGGET);
		registerItemModel(ModItems.LEAD_HELMET);
		registerItemModel(ModItems.LEAD_CHESTPLATE);
		registerItemModel(ModItems.LEAD_LEGGINGS);
		registerItemModel(ModItems.LEAD_BOOTS);
		registerItemModel(ModItems.LEAD_PICKAXE);
		registerItemModel(ModItems.LEAD_AXE);
		registerItemModel(ModItems.LEAD_SWORD);
		registerItemModel(ModItems.LEAD_SHOVEL);
		registerItemBlockModel(ModBlocks.GALLIUM_ORE);
		registerItemBlockModel(ModBlocks.GALLIUM_BLOCK);
		registerItemBlockModel(ModBlocks.GALLIUM_INGOT);
		registerItemBlockModel(ModBlocks.GALLIUM_NUGGET);
		registerItemModel(ModItems.GALLIUM_HELMET);
		registerItemModel(ModItems.GALLIUM_CHESTPLATE);
		registerItemModel(ModItems.GALLIUM_LEGGINGS);
		registerItemModel(ModItems.GALLIUM_BOOTS);
		registerItemModel(ModItems.GALLIUM_PICKAXE);
		registerItemModel(ModItems.GALLIUM_AXE);
		registerItemModel(ModItems.GALLIUM_SWORD);
		registerItemModel(ModItems.GALLIUM_SHOVEL);

	}

	@SideOnly(Side.CLIENT)
	protected static final void registerItemModel(final Item item) {
		ModelLoader.setCustomModelResourceLocation(item, 0, new ModelResourceLocation(item.getRegistryName(), "inventory"));
	}

	@SideOnly(Side.CLIENT)
	protected static final void registerItemBlockModel(final Block block) {
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(block), 0, new ModelResourceLocation(block.getRegistryName(), "inventory"));
	}

}